// This file is generated by Slice Machine. Update with care!

import BookGrid from './BookGrid';
import CallToAction from './CallToAction';

export {
	BookGrid,
	CallToAction,
};

export const components = {
	book_grid: BookGrid,
	call_to_action: CallToAction,
};
